#!/bin/sh /etc/rc.common
# For RedHat and cousins:
# chkconfig: - 99 01
# description: 一款轻量级、功能强大的内网穿透代理服务器。支持tcp、udp流量转发，支持内网http代理、内网socks5代理，同时支持snappy压缩、站点保护、加密传输、多路复用、header修改等。支持web图形化管理，集成多用户模式。
# processname: /usr/local/bin/nps
### BEGIN INIT INFO
# Provides:          /usr/local/bin/nps
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: nps内网穿透代理服务器
# Description:       一款轻量级、功能强大的内网穿透代理服务器。支持tcp、udp流量转发，支持内网http代理、内网socks5代理，同时支持snappy压缩、站点保护、加密传输、多路复用、header修改等。支持web图形化管理，集成多用户模式。
### END INIT INFO

START=99
USE_PROCD=1

_log() {
	local level="$1" ; shift
	local msg="$@"
	logger -p "daemon.$level" -t "$NAME" "$msg"

	echo "[$level] $msg" >&2
}

_info() {
	_log "info" $@
}

_err() {
	_log "err" $@
}

start_service() {
	config_load nps
		logger -t nps 'Starting Nps service' 
		procd_open_instance
    		procd_set_param command /etc/nps/nps "service"
    		#procd_set_param file $tmpconf
    		procd_set_param respawn
    		procd_set_param stdout 1
    		procd_set_param stderr 1
    		procd_close_instance
}